application: beordle
version: 1
runtime: python
api_version: 1

handlers:

- url: /_ah/xmpp/message/chat/
  script: Application/XMPP/core.py
- url: /_ah/mail/.*
  script: app/email/main.py

- url: /_ah/mail/.*
  script: app/email/main.py
 
- url: /
  script: index.py

- url: /.*
  script: core.py
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

inbound_services:
 - mail
 - xmpp_message

derived_file_type:
 - python_precompiled

